### ISSUE TITLE
Is AMI available for eu-central-1? 

### ISSUE THREAD

**Issue by someswarpanda** [aws-quickstart/quickstart-ibm-mq#10]
Could not find an AMI for IBM MQ 9.1.1 on eu-central-1. Is there any plan for availability in this region?

**Comment by jmcguire23** [comment]
The quickstart for IBM MQ currently only supports 5 regions; us-east-1, us-east-2, us-west-2, eu-west-1 and ap-southeast-2. We do not have any immediate plans to support other regions.

**Comment by someswarpanda** [comment]
Ok, thanks!
