### ISSUE TITLE
EFS regions in templates needs updating.

### ISSUE THREAD

**Issue by namloc2001** [aws-quickstart/quickstart-ibm-mq#11]
Hi,

EFS is now available in many more regions than those listed in the following templates:

quickstart-ibm-mq/templates/ibm-mq-master.template (lines 309-322)
quickstart-ibm-mq/templates/ibm-mq.template (lines 275-288)

Could this please be updated to reflect this as we've not been able to deploy to London.

(I'm guessing AMIs for other regions will be required too).

Thanks,

Matt

**Comment by vsnyc** [comment]
@namloc2001 New Regions including London have been added. Resolving this, please open a new issue if you have any questions.

**Comment by namloc2001** [comment]
Hi, I believe the description:

AssertDescription: This Quick Start utilizes Amazon EFS which is only available in the US East (N. Virginia), US East (Ohio), US West (Oregon), EU (Ireland) and Asia Pacific (Sydney) regions. Please launch the stack in one of these regions.

In both templates needs updating as well.

Thanks, Matt
