### ISSUE TITLE
Update Region "AssertDescription" in templates

### ISSUE THREAD

**Issue by namloc2001** [aws-quickstart/quickstart-ibm-mq#14]
Hi, I believe the description:

AssertDescription: This Quick Start utilizes Amazon EFS which is only available in the US East (N. Virginia), US East (Ohio), US West (Oregon), EU (Ireland) and Asia Pacific (Sydney) regions. Please launch the stack in one of these regions.

In both templates (ibm-mq-master.template and ibm-mq.template) needs updating as well.

Thanks, Matt

**Comment by vsnyc** [comment]
Fixed at commit: https://github.com/aws-quickstart/quickstart-ibm-mq/commit/653640bedd1ae845683e39c2c9a7553f3e8dac17
