### ISSUE TITLE
mq-console service won't listen to 9443 due to syntax error in mqwebuser.xml

### ISSUE THREAD

**Issue by utpaludan** [aws-quickstart/quickstart-ibm-mq#26]
Hi,
I have deployed the ibm-mq stack into an existing VPC
Things gets deployed correctly, butI'm not able to connect to the liberty console

I have a problem with a syntax error in /var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml that prevents mq-console.service from starting correctly. The console.log reports :

[AUDIT   ] CWWKG0028A: Processing included configuration resource: /var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml
[ERROR   ] CWWKG0014E: The configuration parser detected an XML syntax error while parsing the root of the configuration and the referenced configuration documents. Error: The value of attribute "name" must not contain the '<' character. File: file:/var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml Line: 100 Column: 12

I can correct it by editing the xml file and remove the < and > in line 100 and the console service can then start up correctly and listen for connections on the 9443 port
But as soon as the mq ec2 instance is replaced by a new one, the change get overwritten.

I can't figure out how the mq installation gets created in the efs file system mounted on the instance and how I can persistantly edit the xml file

Thanks in advance
Ulrik

**Comment by eschu21** [comment]
The xml file is edited by a sed operation in the aws-comfigure-mq script (or something close to that I'm on mobile). If you `which` that script you'll find it.

I fixed this issue by removing any odd characters in my mq username. Try the one the provide in the template in this repo.

**Comment by utpaludan** [comment]
@eschu21, :q!yes I figured out that the sed commands in script configure-mq-aws, isn't being executed if the queue manager has already been setup in the /var/mqm filesystem, which is fine (the settings need to be maintained if a new instance is started)
The sed commands make the change to username and password in /usr/local/bin/starter-registry.xml, if the queue manager hasn't yet been setup and further down in the script /usr/local/bin/starter-registry.xml is being copyed to /var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml (in persistent storage) by the mq-console-setup service. 
When the ec2 instance is stopped and a new ec2 is started, the sed commands isn't executed since the queue manager is already setup in "/var/mqm/qmgrs/${MQ_QMGR_NAME}". That is fine, but later in the script it still copy the unmodifyed /usr/local/bin/starter-registry.xml over the mqwebuser.xml file, overwriting the modications from earlier.
It looks like it does the overwrite when the directory /var/mqm/web/installations/Installation1/angular.persistence isn't present

I'm not sure what should cause angular.persistence to be created

**Comment by eschu21** [comment]
Hmm interesting!

So in fact this solution does not work as intended if that sed operation is executing on each new instance against a persistent configuration.

I just tested, and sure enough my configuration is broken.

did you ever modify the script or do anything to get this resolved?


Thanks!

**Comment by eschu21** [comment]
Thinking about this more, I propose the following fix (unless we figure out where angular.persistance is supposed to come from):

There are 2 main startup scripts:

`/usr/local/bin/configure-mq-aws`
which calls a service mq-console-setup, which runs the script…


`/usr/local/bin/configure-mq-console`

Basically the second time an instance gets launched, the `/var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml` file gets overwritten with the default config file, wherein the username is `<NAME>`, and `<` is an invalid character so the mq console fails to start.

See the following code snippet from `/usr/local/bin/configure-mq-console`:


```
IPADDR="$(ifconfig | grep -A 1 'eth0' | tail -1 | awk '{print $2}')"

if [ ! -d "/var/mqm/web/installations/Installation1/angular.persistence" ]; then
  mv /var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml /var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml.old

  cp /usr/local/bin/starter-registry.xml /var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml

  chmod ug+w /var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml

  sed -i "s/_HOSTNAME_/${IPADDR}/g" /var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml

else
  sed -i "s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/${IPADDR}/" /var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml
fi
```

On subsequent starts, we need the if condition to FAIL, so that it moves to the `else` block. right now it is looking for a file called `angular.persistence`. 

My recommendation is that we do the following:

1. Modify `/usr/local/bin/configure-mq-aws` so that it places a file as its last step, AFTER it executes `systemctl start mq-console-setup:`

Filename: `/var/mqm/web/installations/Installation1/ibmmq.persistence`


2. Modify the script `/usr/local/bin/configure-mq-console` to look for this new file in that if condition instead of `/var/mqm/web/installations/Installation1/angular.persistence`

This would of course have to be done on the AMI.

**Comment by utpaludan** [comment]
Instead of making changes to the AMI (as i'm not aware how is done), I guess we should be able to modify the configure-mq-aws with the changes you suggest, in the same way

**Comment by eschu21** [comment]
for the ami, you would want to take the one provided and make a new one. I may test this out with packer soon.

In the meantime I have taken your code and am testing it.

**Comment by vsnyc** [comment]
@jmcguire23 - Could you please look into this issue. Looks like the IBM MQ AMI needs to be updated. Many thanks!

**Comment by vsnyc** [comment]
Thanks @utpaludan and @eschu21 for reporting the issue, and coming up with a workaround to solve it. 

I'm reaching out to IBM to see if we can get the AMI updated. Will update the post when I hear back.

**Comment by eschu21** [comment]
This would be great!

Side topic, but why exactly is kubelet running on this AMI? it clogs up `journalctl -xe` with errors and as far as I can tell none of this is meant to run in a k8s cluster.

**Comment by craigs-techout** [comment]
@vsnyc - I implemented this quick start a while back and all of a sudden the IBM AMI image is no longer there - Do you what happened to it and if it is in a different place? 

IBM MQ v9.2.0 [BASELINE] - 20200727-103330UTC from Owner 892471419890

**Comment by vsnyc** [comment]
@craigs-techout - Thanks for bringing this up, looks like there was a deprecation time added to the AMIs and we'll need IBM to refresh it.

```
$ ec2di ami-0584dc442ad6b24ed --region eu-west-1
{
    "Images": [
        {
            "Architecture": "x86_64",
            "CreationDate": "2020-07-27T10:38:00.000Z",
            "ImageId": "ami-0584dc442ad6b24ed",
            "ImageLocation": "892471419890/IBM MQ v9.2.0 [BASELINE] - 20200727-103330UTC",
            "ImageType": "machine",
            "Public": true,
            "OwnerId": "892471419890",
            "PlatformDetails": "Linux/UNIX",
            "UsageOperation": "RunInstances",
            "State": "available",
            "BlockDeviceMappings": [
                {
                    "DeviceName": "/dev/sda1",
                    "Ebs": {
                        "DeleteOnTermination": true,
                        "SnapshotId": "snap-098e0e4ea3359ba12",
                        "VolumeSize": 20,
                        "VolumeType": "gp2",
                        "Encrypted": false
                    }
                },
                {
                    "DeviceName": "/dev/sdb",
                    "VirtualName": "ephemeral0"
                },
                {
                    "DeviceName": "/dev/sdc",
                    "VirtualName": "ephemeral1"
                }
            ],
            "Description": "IBM MQ v9.2.0 Trial on Ubuntu 16.04",
            "EnaSupport": true,
            "Hypervisor": "xen",
            "Name": "IBM MQ v9.2.0 [BASELINE] - 20200727-103330UTC",
            "RootDeviceName": "/dev/sda1",
            "RootDeviceType": "ebs",
            "SriovNetSupport": "simple",
            "VirtualizationType": "hvm",
            "DeprecationTime": "2022-07-27T10:38:00.000Z"
        }
    ]
}
```

**Comment by craigs-techout** [comment]
@vsnyc Thanks for responding - do you have a contact with IBM to refresh it?

**Comment by jmcguire23** [comment]
@craigs-techout @vsnyc I have unset the deprecation time on all AMIs, they should be deployable again.

**Comment by vsnyc** [comment]
Thanks @jmcguire23 , appreciate the quick response. For everyone's benefit, this is what caused the issue: https://aws.amazon.com/about-aws/whats-new/2022/03/amazon-machine-images-public-visibility-two-years/. For long lived public AMIs, a deprecation date has automatically been set.

**Comment by craigs-techout** [comment]
> @craigs-techout @vsnyc I have unset the deprecation time on all AMIs, they should be deployable again.

@jmcguire23 Thank you - I am able to access the image again.

**Comment by matthewkmayer** [comment]
@jmcguire23 @vsnyc Thanks for fixing the visibility on the AMI! 

It appears to be missing again: `ami-0eeb95a87a14983db` with location of `892471419890/IBM MQ v9.2.0 [BASELINE] - 20200727-103330UTC` isn't available in us-east-1 again. Can you reset the image visibility again please? Thanks!

**Comment by jmcguire23** [comment]
@matthewkmayer thank you for bringing this to our attention. I had previously removed the deprecation time on these images, but seemingly this has shown up again.

@vsnyc I have tried removing the deprecation time again as per AWS documentation, but after a short time this is still showing on the description for the image. Is there a cache timeout period?

**Comment by jmcguire23** [comment]
@matthewkmayer Please check whether the AMI is appearing for you now, I have extended the deprecation time of the current AMIs
@vsnyc It appears the AMI deprecation was reset, was this something known to be happening from AWS?

**Comment by matthewkmayer** [comment]
@jmcguire23 yes, the image is back to being available, thank you! 👍

**Comment by vsnyc** [comment]
Closing old issues. The solution has been updated to use [IBM MQ Helm chart](https://github.com/ibm-messaging/mq-helm) for deployment.
