### ISSUE TITLE
IBM MQ license issue with autoscaling

### ISSUE THREAD

**Issue by engmohammedelkasrawy** [aws-quickstart/quickstart-ibm-mq#28]
after licensing the IBM MQ application if I try and terminate the instance and let the autoscaling system get a new instance up the IBM MQ doesn't work and when I run this command:
`systemctl status mq@IBM_MQ_MNGR`
I get this error with the license:
`● mq@TEST_DI_QMGR.service - IBM MQ queue manager TEST_DI_QMGR
   Loaded: loaded (/etc/systemd/system/mq@.service; indirect; vendor preset: enabled)
  Drop-In: /etc/systemd/system/mq@TEST_DI_QMGR.service.d
           └─mount-var-mqm.conf
   Active: failed (Result: exit-code) since Wed 2022-10-26 14:48:19 UTC; 56min ago

Oct 26 14:48:18 ip-10-9-0-12 systemd[1]: Starting IBM MQ queue manager TEST_DI_QMGR...
Oct 26 14:48:19 ip-10-9-0-12 MQSeries[2260]: FFST record created in /var/mqm/errors/AMQ2260.0.FDC
Oct 26 14:48:19 ip-10-9-0-12 systemd[1]: mq@TEST_DI_QMGR.service: Control process exited, code=exited status=71
Oct 26 14:48:19 ip-10-9-0-12 strmqm[2260]: AMQ7128E: No license installed for this copy of IBM MQ.
Oct 26 14:48:19 ip-10-9-0-12 systemd[1]: mq@TEST_DI_QMGR.service: Failed with result 'exit-code'.
Oct 26 14:48:19 ip-10-9-0-12 systemd[1]: Failed to start IBM MQ queue manager TEST_DI_QMGR.`
any help here?

**Comment by jmcguire23** [comment]
Does the command `dspmq` return anything?

**Comment by engmohammedelkasrawy** [comment]
this is the output
root@ip-10-9-0-29:/var/snap/amazon-ssm-agent/6312# dspmq
QMNAME(TEST_DI_QMGR)                                      STATUS(Ended unexpectedly)

**Comment by jmcguire23** [comment]
Check for error logs in the directory `/var/mqm/qmgrs/<qmname>/errors`

**Comment by umamaheshsp** [comment]
Open this file /var/mqm/errors/AMQ2260.0.FDC and check the error reported

**Comment by jmcguire23** [comment]
If you are still facing problems, ensure you followed the instructions here on how to apply a license to trial instance https://www.ibm.com/docs/en/ibm-mq/9.2?topic=linux-converting-trial-license

**Comment by engmohammedelkasrawy** [comment]
Hello @jmcguire23 ,
I followed the licensing instructions from IBM and the license is working fine but this is not the issue.
the issue is after any scaling actions let's say that the instance got terminated for any reason and another one got spun up by the autoscaling group here is where the issue happens the application gets down and this error appears!!

**Comment by engmohammedelkasrawy** [comment]
Hello,
I searched for the error I'm getting and this is what IBM suggests to do. can you help me clarify the needed action here?
https://www.ibm.com/support/pages/amq6118-unable-create-wmq-queue-manager

**Comment by jmcguire23** [comment]
Have you tried manually restarting the queue manager? https://www.ibm.com/docs/en/ibm-mq/9.3?topic=reference-strmqm-start-queue-manager

Did you find any further logs from the FDC file `/var/mqm/errors/AMQ2260.0.FDC` ?

**Comment by engmohammedelkasrawy** [comment]
I tried restarting the queue manager and yes issue didn't get resolved
this is the error file I can't understand anything from it:
[AMQ2260.0.txt](https://github.com/aws-quickstart/quickstart-ibm-mq/files/9903553/AMQ2260.0.txt)

**Comment by vsnyc** [comment]
Closing old issues. The solution has been updated to use [IBM MQ Helm chart](https://github.com/ibm-messaging/mq-helm) for deployment.
