### ISSUE TITLE
Documentation needs complete rewrite

### ISSUE THREAD

**Issue by kallu** [aws-quickstart/quickstart-ibm-mq#32]
README.md is referring to "IBM MQ on the AWS Cloud Quick Start Reference Deployment" that is about EC2 based architecture. Now as deployment has been rewritten for EKS, docs are in need of rewrite as well.
> For architectural details and step-by-step instructions, refer to the deployment guide https://aws-quickstart.github.io/quickstart-ibm-mq/

**Comment by vsnyc** [comment]
The deployment guide is refreshed: https://aws-quickstart.github.io/quickstart-ibm-mq/
