### ISSUE TITLE
Update the Helm app name

### ISSUE THREAD

**Issue by arvind-cb** [aws-quickstart/quickstart-ibm-mq#39]
Hi Team,
Could you please share the steps to change the name of the helm app?
The current code uses "securehelmapp" as the helm app name, referenced in various other places.
We want to make this name dynamic (eg: devmqapp or preprodmqapp).

We tried changing the name from "securehelmapp" to "devqm", in the <repo>/samples/AWSEKSPartnerSolution/deploy/install.sh, 
however, after the cluster was deployed successfully, the mq web console started timing out.

Please let us know the scripts and files which need changes so that we can follow the same.

**Comment by chughts** [comment]
it looks like the name `secureapphelm` gets propagated, so you will need to ensure all references are likewise updated. Which will also allow the readiness and startup probes to work. 

eg. `secureapphelm-ibm-mq-loadbalancer`, `data-secureapphelm-ibm-mq-0`, `data-secureapphelm-ibm-mq-1`, 

As a minimum, I found references in this repo:

- https://github.com/aws-quickstart/quickstart-ibm-mq/scripts/install.sh


in the mq-helm repo:
- samples/AWSEKSPartnerSolution/deploy/install.sh
- samples/AWSEKSPartnerSolution/deploy/cleanup.sh

and other references in the mq-helm repo:
- samples/AWSEKSPartnerSolution/test/ccdt_template.json
- samples/AWSEKSPartnerSolution/test/sendMessage.sh
- samples/AWSEKSPartnerSolution/test/getMessage.sh

**Comment by arvind-cb** [comment]
Hi Team, Thanks for the quick reply.
We had already changed the "install.sh" and "Cleanup.sh", but that didn't help. 
We want to understand why the console is not working with the helm app name change. 
I am also attaching the web console log from one of the containers. Please review and let us know if any issues are causing webconsole time outs.
[webconsole.log.pdf](https://github.com/aws-quickstart/quickstart-ibm-mq/files/12915323/webconsole.log.pdf)
